### PR TITLE
Build database infrasturcture

### PR DESCRIPTION
**Pull request by osopromadze**
issue https://github.com/mehai/argolib/issues/2

**Create database infrastructure using either hibernate or mysql having following tables:**

- Users

- Books

- Reviews

- Reservations

All identified by id - primary key.

**Relationships:**
**Books** - ONE to MANY - **Reservations, Reviews**

**Users** - ONE to MANY - **Reservations, Reviews**

### CODE REVIEW

**Comment by mehai** [comment]
Hello!
Thank you for your contribution. I did not expect people to get involved in this project so fast. I took a look at your script and it's what we need.
However, We will be using Spring Security for authentication so it would be great if you could do the next things before the merge:

- Add an enabled field in the user table (Spring Security)

- Add an authorities table with an ONE-to-ONE relationship with the users table (Spring Security)

- Drop isbn colomn in books table and add category colomn

Thank you for your work!

**Comment by osopromadze** [comment]
Hello,
Will try to find time tomorrow and do it. 
 

- Category could be another table with ONE to MANY relationship with books table, or just column in books table

**Comment by mehai** [comment]
> Hello,
> Will try to find time tomorrow and do it.
> 
>     * Category could be another table with ONE to MANY relationship with books table, or just column in books table

While it makes sense to be a separate table, for the sake of simplicity let's just leave it a colomn in books table for now. Thank you!

**Review by osopromadze — COMMENTED** [review]
> Hello!
> Thank you for your contribution. I did not expect people to get involved in this project so fast. I took a look at your script and it's what we need.
> However, We will be using Spring Security for authentication so it would be great if you could do the next things before the merge:
> 
> * Add an enabled field in the user table (Spring Security)
> * Add an authorities table with an ONE-to-ONE relationship with the users table (Spring Security)
> * Drop isbn colomn in books table and add category colomn
> 
> Thank you for your work!

**DONE**

Also created entities, repositories, services, controllers for tables

**Comment by mehai** [comment]
> > Hello!
> > Thank you for your contribution. I did not expect people to get involved in this project so fast. I took a look at your script and it's what we need.
> > However, We will be using Spring Security for authentication so it would be great if you could do the next things before the merge:
> > 
> > * Add an enabled field in the user table (Spring Security)
> > * Add an authorities table with an ONE-to-ONE relationship with the users table (Spring Security)
> > * Drop isbn colomn in books table and add category colomn
> > 
> > Thank you for your work!
> 
> **DONE**
> 
> Also created entities, repositories, services, controllers for tables

First of all, thank you for all your work! You've done the job I would have done in probably 2 weeks. I am a beginner in Spring technologies and in web development and I'm already learning a lot from your work here.
I will be soon posting a CONTRIBUTIONS file where I'll be establishing a few rules so that we can be more organized in our word (if you still want to help in the future). Until then, don't hesitate to contact me if you want to propose certain issues.
Thank you again!

**Comment by osopromadze** [comment]
> > > Hello!
> > > Thank you for your contribution. I did not expect people to get involved in this project so fast. I took a look at your script and it's what we need.
> > > However, We will be using Spring Security for authentication so it would be great if you could do the next things before the merge:
> > > 
> > > * Add an enabled field in the user table (Spring Security)
> > > * Add an authorities table with an ONE-to-ONE relationship with the users table (Spring Security)
> > > * Drop isbn colomn in books table and add category colomn
> > > 
> > > Thank you for your work!
> > 
> > 
> > **DONE**
> > Also created entities, repositories, services, controllers for tables
> 
> First of all, thank you for all your work! You've done the job I would have done in probably 2 weeks. I am a beginner in Spring technologies and in web development and I'm already learning a lot from your work here.
> I will be soon posting a CONTRIBUTIONS file where I'll be establishing a few rules so that we can be more organized in our word (if you still want to help in the future). Until then, don't hesitate to contact me if you want to propose certain issues.
> Thank you again!

Time to time will try to contribute to your project, and it is good idea everything to be more organized. 

I have some experience in java and spring but learning new things too always.

Thanks to you and good luck on your developer journey.

**Pull request merged**
